services:
  dummy:
    image: hashicorp/http-echo
    command: ['-text=pong']
  server:
    build: .
    image: portkey/server:local
    depends_on:
      - dummy
    ports:
      - '8080:8080'
    volumes:
      - ./auth.yaml:/auth.yaml:ro
      - ./data:/data
    entrypoint: []
    command:
      [
        '/portkey-server',
        '-addr',
        ':8080',
        '--auth-file',
        '/auth.yaml',
        '--enable-web-ui',
        '--log-store',
        'sqlite',
        '--log-db',
        '/data/logs.db',
      ]
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: portkey/client:local
    depends_on:
      - server
    entrypoint: []
    command:
      [
        '/portkey-client',
        '--server',
        'http://server:8080',
        '--subdomain',
        'myapp',
        '--host',
        'dummy',
        '--port',
        '5678',
        '--auth-token',
        'admin456',
      ]
    network_mode: service:server
