# Build stage
FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /portkey-cli ./cmd/client

# Final minimal image
FROM scratch
COPY --from=build /portkey-cli /portkey-cli
ENTRYPOINT ["/portkey-cli"]
