# Build stage
FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o portkey-cli ./cmd/client

# Final stage
FROM scratch
COPY --from=build /src/portkey-cli /portkey-cli
ENTRYPOINT ["/portkey-cli"]
