name: Build

# Triggered from dedicated draft-release branch to prepare artifacts for each release cycle
on:
  push:
    branches:
      - draft-release

concurrency: build

jobs:
  update-draft-release:
    name: Create / update draft release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: read
    outputs:
      tag_name: ${{ steps.update-release-content.outputs.tag_name }}
    steps:
      - name: Update release content
        id: update-release-content
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: 'draft-release'

  cli:
    needs: update-draft-release
    name: Build CLI
    uses: ./.github/workflows/build-cli.yml
    with:
      release-tag: ${{ needs.update-draft-release.outputs.tag_name }}

  server:
    needs: update-draft-release
    name: Build Server
    uses: ./.github/workflows/build-server.yml
    with:
      release-tag: ${{ needs.update-draft-release.outputs.tag_name }}