name: Test

on:
  push:
    branches-ignore:
      - draft-release
  pull_request:

jobs:
  unit-and-integration-tests:
    name: Run unit & e2e tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-go-

      - name: Run tests
        run: make test

  update-draft-release-branch:
    needs:
      - unit-and-integration-tests
    if: github.ref == 'refs/heads/main'
    name: Update draft release branch
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Update
        uses: alice-biometrics/github-push-action@v0.7.0
        with:
          branch: draft-release
          force: true
          github_token: ${{ secrets.RELEASE_TOKEN }}
